FROM maven:3.9.8-eclipse-temurin-21 AS build
WORKDIR /app

COPY pom.xml .
RUN mvn dependency:go-offline -B

COPY src ./src
RUN mvn clean package -DskipTests

FROM eclipse-temurin:21-jdk-jammy
WORKDIR /app

COPY --from=build /app/target/*.jar service-discovery-eureka.jar

EXPOSE 8761

ENTRYPOINT ["java", "-jar", "/app/service-discovery-eureka.jar"]